import { z } from 'zod';
import { ExtensionsSchema, JsonValueSchema } from '../common/json.js';
import {
  AddressSchema,
  ConversationIdSchema,
  CorrelationIdSchema,
  MessageIdSchema,
  SessionIdSchema,
} from '../common/ids.js';
import {
  DurationMsSchema,
  MediaTypeSchema,
  RedactionRuleSchema,
  SchemaVersionSchema,
  SemVerSchema,
  SensitivitySchema,
  SlugSchema,
  TimestampSchema,
} from '../common/primitives.js';
import { ActorRefSchema } from '../domain/actor.js';
import { ContractErrorSchema } from '../common/errors.js';

/**
 * Engine-to-engine message envelope
 * =================================
 * One envelope shape covers every hop between engines, whether it travels as a
 * direct in-process call (request/response) or as a published event
 * (fire-and-forget). Keeping the shape identical is what makes it possible to
 * record, replay and audit both paths with a single writer (ADR-0003, ADR-0007).
 *
 * Transport-independence is deliberate: today everything is in-process, but the
 * envelope carries enough (`source`, `destination`, `ttlMs`, `deliveryMode`,
 * `idempotencyKey`, tracing headers) to survive a move to worker threads or a
 * local socket without a contract change.
 */

/* -------------------------------------------------------------------------- */
/* Naming                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Operation / event name in dotted form: `<domain>.<entity>.<action>`, e.g.
 * `session.step.completed`, `model.completion.create`. Wildcards are only legal
 * in subscriptions, never in an emitted message.
 */
export const MessageNameSchema = z
  .string()
  .min(3)
  .max(128)
  .regex(/^[a-z][a-z0-9-]*(\.[a-z0-9-]+){1,4}$/)
  .describe('Dotted message name, e.g. "session.step.completed"');
export type MessageName = z.infer<typeof MessageNameSchema>;

/** Subscription pattern: dotted name where `*` matches one segment and `**` matches the rest. */
export const TopicPatternSchema = z
  .string()
  .min(1)
  .max(128)
  .regex(/^(\*\*|([a-z0-9-]+|\*)(\.([a-z0-9-]+|\*))*(\.\*\*)?)$/)
  .describe('Subscription pattern, e.g. "session.*.completed" or "audit.**"');
export type TopicPattern = z.infer<typeof TopicPatternSchema>;

/* -------------------------------------------------------------------------- */
/* Shared header block                                                         */
/* -------------------------------------------------------------------------- */

export const DeliveryModeSchema = z
  .enum(['at-most-once', 'at-least-once'])
  .describe('At-least-once requires handlers to be idempotent via idempotencyKey');

export const PrioritySchema = z.enum(['low', 'normal', 'high', 'critical']);

/** W3C Trace Context, so a session can be traced end to end. */
export const TraceContextSchema = z.strictObject({
  traceparent: z
    .string()
    .regex(/^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$/)
    .describe('W3C traceparent header'),
  tracestate: z.string().max(512).optional(),
});
export type TraceContext = z.infer<typeof TraceContextSchema>;

/**
 * Fields common to every envelope kind. Split out so the four kinds below stay
 * a discriminated union while sharing one definition.
 */
export const MessageHeaderSchema = z.strictObject({
  /** Contract version of the envelope itself. */
  schemaVersion: SchemaVersionSchema,
  id: MessageIdSchema,
  name: MessageNameSchema,
  /** Emitting engine (and optionally instance). */
  source: AddressSchema,
  /** Wall-clock creation time at the source. */
  createdAt: TimestampSchema,
  /**
   * Groups every message belonging to one logical operation. Generated by the
   * first message in a chain and copied by everything downstream.
   */
  correlationId: CorrelationIdSchema,
  /** Id of the message that directly caused this one. */
  causationId: MessageIdSchema.optional(),
  sessionId: SessionIdSchema.optional(),
  conversationId: ConversationIdSchema.optional(),
  actor: ActorRefSchema.optional(),
  trace: TraceContextSchema.optional(),
  priority: PrioritySchema.optional(),
  deliveryMode: DeliveryModeSchema.optional(),
  /** Deduplication key for at-least-once delivery and safe retries. */
  idempotencyKey: z.string().min(1).max(200).optional(),
  /** 1 for the first attempt. */
  attempt: z.int().min(1).optional(),
  /** Message is stale after `createdAt + ttlMs`; receivers SHOULD drop it. */
  ttlMs: DurationMsSchema.optional(),
  contentType: MediaTypeSchema.optional(),
  /** Version of the payload schema, independent of the envelope version. */
  payloadSchema: z
    .strictObject({
      /** Registered contract schema id, e.g. `Finding` or `model.CompletionRequest`. */
      id: z.string().max(128),
      version: SemVerSchema.optional(),
    })
    .optional(),
  sensitivity: SensitivitySchema.optional(),
  /** Pointers the audit/telemetry sinks must redact before persisting. */
  redactions: z.array(RedactionRuleSchema).max(64).optional(),
  /** Free-form transport headers; never load-bearing for business logic. */
  headers: z.record(z.string().max(64), z.string().max(1_024)).optional(),
  extensions: ExtensionsSchema.optional(),
});
export type MessageHeader = z.infer<typeof MessageHeaderSchema>;

/* -------------------------------------------------------------------------- */
/* Kinds                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * `request` — a directed call expecting exactly one `response`.
 * Used for orchestration → model gateway, orchestration → tooling, etc.
 * In-process these are plain function calls; the envelope is still built so the
 * audit engine sees the same record it would over a socket.
 */
export const RequestEnvelopeSchema = MessageHeaderSchema.extend({
  kind: z.literal('request'),
  destination: AddressSchema,
  /** Address the responder must reply to; defaults to `source`. */
  replyTo: AddressSchema.optional(),
  /** Caller-side deadline. Responder SHOULD abort when exceeded. */
  timeoutMs: DurationMsSchema.optional(),
  /** Caller asks the responder to stream partial results. */
  stream: z.boolean().optional(),
  payload: JsonValueSchema,
}).meta({ id: 'RequestEnvelope', title: 'Request envelope' });
export type RequestEnvelope = z.infer<typeof RequestEnvelopeSchema>;

/**
 * `response` — the single terminal reply to a `request`.
 * `status` is redundant with `error` on purpose: consumers branch on one field.
 */
export const ResponseEnvelopeSchema = MessageHeaderSchema.extend({
  kind: z.literal('response'),
  destination: AddressSchema,
  /** Id of the request being answered. */
  inReplyTo: MessageIdSchema,
  status: z.enum(['ok', 'error', 'partial', 'cancelled']),
  payload: JsonValueSchema.optional(),
  error: ContractErrorSchema.optional(),
  /** Server-side processing time, for telemetry without extra plumbing. */
  durationMs: DurationMsSchema.optional(),
}).meta({ id: 'ResponseEnvelope', title: 'Response envelope' });
export type ResponseEnvelope = z.infer<typeof ResponseEnvelopeSchema>;

/**
 * `event` — a fact that already happened, broadcast to zero or more subscribers.
 * Events MUST be named in the past tense and MUST NOT be used to ask for work.
 */
export const EventEnvelopeSchema = MessageHeaderSchema.extend({
  kind: z.literal('event'),
  /** Optional: events are normally broadcast (`*`). */
  destination: AddressSchema.optional(),
  /** Topic the bus routes on; defaults to `name` when omitted. */
  topic: MessageNameSchema.optional(),
  /** Aggregate this event is about, e.g. a session or finding id. */
  subject: z.string().max(128).optional(),
  /** Per-subject monotonic sequence, for gap detection during replay. */
  sequence: z.int().min(0).optional(),
  payload: JsonValueSchema,
}).meta({ id: 'EventEnvelope', title: 'Event envelope' });
export type EventEnvelope = z.infer<typeof EventEnvelopeSchema>;

/**
 * `stream` — an ordered chunk belonging to a streaming response
 * (model tokens, long-running tool output). Terminated by `final: true`
 * or by a `response` with a matching `inReplyTo`.
 */
export const StreamChunkEnvelopeSchema = MessageHeaderSchema.extend({
  kind: z.literal('stream'),
  destination: AddressSchema,
  inReplyTo: MessageIdSchema,
  /** 0-based chunk index; receivers MUST reorder or reject gaps. */
  sequence: z.int().min(0),
  final: z.boolean(),
  payload: JsonValueSchema.optional(),
  error: ContractErrorSchema.optional(),
}).meta({ id: 'StreamChunkEnvelope', title: 'Stream chunk envelope' });
export type StreamChunkEnvelope = z.infer<typeof StreamChunkEnvelopeSchema>;

/** Any message that can appear on a boundary. */
export const EngineMessageSchema = z
  .discriminatedUnion('kind', [
    RequestEnvelopeSchema,
    ResponseEnvelopeSchema,
    EventEnvelopeSchema,
    StreamChunkEnvelopeSchema,
  ])
  .meta({
    id: 'EngineMessage',
    title: 'Engine message',
    description: 'Transport-independent envelope for every engine-to-engine interaction.',
  });
export type EngineMessage = z.infer<typeof EngineMessageSchema>;

/* -------------------------------------------------------------------------- */
/* Typed helpers                                                               */
/* -------------------------------------------------------------------------- */

/** Narrows a request envelope to a concrete payload schema. */
export const requestOf = <T extends z.ZodType>(payload: T) =>
  RequestEnvelopeSchema.extend({ payload });

/** Narrows a successful response envelope to a concrete payload schema. */
export const responseOf = <T extends z.ZodType>(payload: T) =>
  ResponseEnvelopeSchema.extend({ payload: payload.optional() });

/** Narrows an event envelope to a concrete payload schema. */
export const eventOf = <T extends z.ZodType>(payload: T) => EventEnvelopeSchema.extend({ payload });

/** Typed view over an envelope whose payload has been validated. */
export type TypedRequest<P> = Omit<RequestEnvelope, 'payload'> & { payload: P };
export type TypedResponse<P> = Omit<ResponseEnvelope, 'payload'> & { payload?: P };
export type TypedEvent<P> = Omit<EventEnvelope, 'payload'> & { payload: P };

/** Convenience alias used by engine interfaces. */
export type MessageKind = EngineMessage['kind'];

/** Names of engine capabilities addressable by request/response. */
export const OperationNameSchema = SlugSchema.describe('Direct-call operation name');
